# Generated by Django 4.1.5 on 2023-03-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopstore', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
