# Generated by Django 4.1.5 on 2023-03-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopstore', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='photo',
        ),
    ]
